// Scenario data
export const scenarioDescriptions = [
    { scenarioId: "SN001", description: "Goods at standard rate to registered buyers" },
    { scenarioId: "SN002", description: "Goods at standard rate to unregistered buyers" },
    { scenarioId: "SN003", description: "Sale of Steel (Melted and Re-Rolled)" },
    { scenarioId: "SN004", description: "Sale by Ship Breakers" },
    { scenarioId: "SN005", description: "Reduced rate sale" },
    { scenarioId: "SN006", description: "Exempt goods sale" },
    { scenarioId: "SN007", description: "Zero rated sale" },
    { scenarioId: "SN008", description: "Sale of 3rd schedule goods" },
    { scenarioId: "SN009", description: "Cotton Spinners purchase from Cotton Ginners" },
    { scenarioId: "SN010", description: "Mobile Operators adds Sale (Telecom Sector)" },
    { scenarioId: "SN011", description: "Toll Manufacturing sale by Steel sector" },
    { scenarioId: "SN012", description: "Sale of Petroleum products" },
    { scenarioId: "SN013", description: "Electricity Supply to Retailers" },
    { scenarioId: "SN014", description: "Sale of Gas to CNG stations" },
    { scenarioId: "SN015", description: "Sale of mobile phones" },
    { scenarioId: "SN016", description: "Processing / Conversion of Goods" },
    { scenarioId: "SN017", description: "Sale of Goods where FED is charged in ST mode" },
    { scenarioId: "SN018", description: "Sale of Services where FED is charged in ST mode" },
    { scenarioId: "SN019", description: "Sale of Services" },
    { scenarioId: "SN020", description: "Sale of Electric Vehicles" },
    { scenarioId: "SN021", description: "Sale of Cement / Concrete Block" },
    { scenarioId: "SN022", description: "Sale of Potassium Chlorate" },
    { scenarioId: "SN023", description: "Sale of CNG" },
    { scenarioId: "SN024", description: "Goods sold that are listed in SRO 297(1)/2023" },
    { scenarioId: "SN025", description: "Drugs sold at fixed ST rate under serial 81 of Eighth Schedule Table 1" },
    { scenarioId: "SN026", description: "Sale to End Consumer by retailers (Standard Rate)" },
    { scenarioId: "SN027", description: "Sale to End Consumer by retailers (3rd Schedule Goods)" },
    { scenarioId: "SN028", description: "Sale to End Consumer by retailers (Reduced Rate)" },
  ]
  
  // Business Activity Sector Scenarios
  export const businessActivitySectorScenarios = [
    {
      businessActivity: "Manufacturer",
      sector: "All Other Sectors",
      scenarios: ["SN001", "SN002", "SN005", "SN006", "SN007", "SN015", "SN016", "SN017", "SN021", "SN022", "SN024"],
    },
    { businessActivity: "Manufacturer", sector: "Steel", scenarios: ["SN003", "SN004", "SN011"] },
    {
      businessActivity: "Manufacturer",
      sector: "FMCG",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN008",
      ],
    },
    {
      businessActivity: "Manufacturer",
      sector: "Textile",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN009",
      ],
    },
    {
      businessActivity: "Manufacturer",
      sector: "Telecom",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN010",
      ],
    },
    {
      businessActivity: "Manufacturer",
      sector: "Petroleum",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN012",
      ],
    },
    {
      businessActivity: "Manufacturer",
      sector: "Electricity Distribution",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN013",
      ],
    },
    {
      businessActivity: "Manufacturer",
      sector: "Gas Distribution",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN014",
      ],
    },
    {
      businessActivity: "Manufacturer",
      sector: "Services",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN018",
        "SN019",
      ],
    },
    {
      businessActivity: "Manufacturer",
      sector: "Automobile",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN020",
      ],
    },
    {
      businessActivity: "Manufacturer",
      sector: "CNG Stations",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN023",
      ],
    },
    {
      businessActivity: "Manufacturer",
      sector: "Pharmaceuticals",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN025",
      ],
    },
    {
      businessActivity: "Manufacturer",
      sector: "Wholesale / Retails",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN026",
        "SN027",
        "SN028",
        "SN008",
      ],
    },
    {
      businessActivity: "Importer",
      sector: "All Other Sectors",
      scenarios: ["SN001", "SN002", "SN005", "SN006", "SN007", "SN015", "SN016", "SN017", "SN021", "SN022", "SN024"],
    },
    {
      businessActivity: "Importer",
      sector: "Steel",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN003",
        "SN004",
        "SN011",
      ],
    },
    {
      businessActivity: "Importer",
      sector: "FMCG",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN008",
      ],
    },
    {
      businessActivity: "Retailer",
      sector: "All Other Sectors",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN026",
        "SN027",
        "SN028",
        "SN008",
      ],
    },
    { businessActivity: "Retailer", sector: "Steel", scenarios: ["SN003", "SN004", "SN011"] },
    { businessActivity: "Retailer", sector: "FMCG", scenarios: ["SN026", "SN027", "SN028", "SN008"] },
    { businessActivity: "Retailer", sector: "Textile", scenarios: ["SN009", "SN026", "SN027", "SN028", "SN008"] },
    { businessActivity: "Retailer", sector: "Telecom", scenarios: ["SN010", "SN026", "SN027", "SN028", "SN008"] },
    { businessActivity: "Retailer", sector: "Petroleum", scenarios: ["SN012", "SN026", "SN027", "SN028", "SN008"] },
    {
      businessActivity: "Retailer",
      sector: "Electricity Distribution",
      scenarios: ["SN013", "SN026", "SN027", "SN028", "SN008"],
    },
    {
      businessActivity: "Retailer",
      sector: "Gas Distribution",
      scenarios: ["SN014", "SN026", "SN027", "SN028", "SN008"],
    },
    {
      businessActivity: "Retailer",
      sector: "Services",
      scenarios: ["SN018", "SN019", "SN026", "SN027", "SN028", "SN008"],
    },
    { businessActivity: "Retailer", sector: "Automobile", scenarios: ["SN020", "SN026", "SN027", "SN028", "SN008"] },
    { businessActivity: "Retailer", sector: "CNG Stations", scenarios: ["SN023", "SN026", "SN027", "SN028", "SN008"] },
    { businessActivity: "Retailer", sector: "Pharmaceuticals", scenarios: ["SN025", "SN026", "SN027", "SN028", "SN008"] },
    { businessActivity: "Retailer", sector: "Wholesale / Retails", scenarios: ["SN026", "SN027", "SN028", "SN008"] },
    {
      businessActivity: "Service Provider",
      sector: "All Other Sectors",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN018",
        "SN019",
      ],
    },
    { businessActivity: "Service Provider", sector: "Steel", scenarios: ["SN003", "SN004", "SN011", "SN018", "SN019"] },
    { businessActivity: "Service Provider", sector: "FMCG", scenarios: ["SN008", "SN018", "SN019"] },
    { businessActivity: "Service Provider", sector: "Textile", scenarios: ["SN009", "SN018", "SN019"] },
    { businessActivity: "Service Provider", sector: "Telecom", scenarios: ["SN010", "SN018", "SN019"] },
    { businessActivity: "Service Provider", sector: "Petroleum", scenarios: ["SN012", "SN018", "SN019"] },
    { businessActivity: "Service Provider", sector: "Electricity Distribution", scenarios: ["SN013", "SN018", "SN019"] },
    { businessActivity: "Service Provider", sector: "Gas Distribution", scenarios: ["SN014", "SN018", "SN019"] },
    { businessActivity: "Service Provider", sector: "Services", scenarios: ["SN018", "SN019"] },
    { businessActivity: "Service Provider", sector: "Automobile", scenarios: ["SN020", "SN018", "SN019"] },
    { businessActivity: "Service Provider", sector: "CNG Stations", scenarios: ["SN023", "SN018", "SN019"] },
    { businessActivity: "Service Provider", sector: "Pharmaceuticals", scenarios: ["SN025", "SN018", "SN019"] },
    {
      businessActivity: "Service Provider",
      sector: "Wholesale / Retails",
      scenarios: ["SN026", "SN027", "SN028", "SN008", "SN018", "SN019"],
    },
    {
      businessActivity: "Other",
      sector: "All Other Sectors",
      scenarios: ["SN001", "SN002", "SN005", "SN006", "SN007", "SN015", "SN016", "SN017", "SN021", "SN022", "SN024"],
    },
    {
      businessActivity: "Other",
      sector: "Steel",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN003",
        "SN004",
        "SN011",
      ],
    },
    {
      businessActivity: "Other",
      sector: "FMCG",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN008",
      ],
    },
    {
      businessActivity: "Other",
      sector: "Textile",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN009",
      ],
    },
    {
      businessActivity: "Other",
      sector: "Telecom",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN010",
      ],
    },
    {
      businessActivity: "Other",
      sector: "Petroleum",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN012",
      ],
    },
    {
      businessActivity: "Other",
      sector: "Electricity Distribution",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN013",
      ],
    },
    {
      businessActivity: "Other",
      sector: "Gas Distribution",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN014",
      ],
    },
    {
      businessActivity: "Other",
      sector: "Services",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN018",
        "SN019",
      ],
    },
    {
      businessActivity: "Other",
      sector: "Automobile",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN020",
      ],
    },
    {
      businessActivity: "Other",
      sector: "CNG Stations",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN023",
      ],
    },
    {
      businessActivity: "Other",
      sector: "Pharmaceuticals",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN025",
      ],
    },
    {
      businessActivity: "Other",
      sector: "Wholesale / Retails",
      scenarios: [
        "SN001",
        "SN002",
        "SN005",
        "SN006",
        "SN007",
        "SN015",
        "SN016",
        "SN017",
        "SN021",
        "SN022",
        "SN024",
        "SN026",
        "SN027",
        "SN028",
        "SN008",
      ],
    },
  ]

  // Default provinces fallback
export const defaultProvinces = [
    { stateProvinceCode: 2, stateProvinceDesc: "BALOCHISTAN" },
    { stateProvinceCode: 4, stateProvinceDesc: "AZAD JAMMU AND KASHMIR" },
    { stateProvinceCode: 5, stateProvinceDesc: "CAPITAL TERRITORY" },
    { stateProvinceCode: 6, stateProvinceDesc: "KHYBER PAKHTUNKHWA" },
    { stateProvinceCode: 7, stateProvinceDesc: "PUNJAB" },
    { stateProvinceCode: 8, stateProvinceDesc: "SINDH" },
    { stateProvinceCode: 9, stateProvinceDesc: "GILGIT BALTISTAN" },
  ]

  export const defaultTransType = [
    {
      "transactioN_TYPE_ID": 75,
      "transactioN_DESC": "Goods at standard rate (default)"
    },
    {
      "transactioN_TYPE_ID": 24,
      "transactioN_DESC": "Goods at Reduced Rate"
    },
    {
      "transactioN_TYPE_ID": 80,
      "transactioN_DESC": "Goods at zero-rate"
    },
    {
      "transactioN_TYPE_ID": 85,
      "transactioN_DESC": "Petroleum Products"
    },
    {
      "transactioN_TYPE_ID": 62,
      "transactioN_DESC": "Electricity Supply to Retailers"
    },
    {
      "transactioN_TYPE_ID": 129,
      "transactioN_DESC": "SIM"
    },
    {
      "transactioN_TYPE_ID": 77,
      "transactioN_DESC": "Gas to CNG stations"
    },
    {
      "transactioN_TYPE_ID": 122,
      "transactioN_DESC": "Mobile Phones"
    },
    {
      "transactioN_TYPE_ID": 25,
      "transactioN_DESC": "Processing/Conversion of Goods"
    },
    {
      "transactioN_TYPE_ID": 23,
      "transactioN_DESC": " 3rd Schedule Goods "
    },
    {
      "transactioN_TYPE_ID": 21,
      "transactioN_DESC": "Goods (FED in ST Mode)"
    },
    {
      "transactioN_TYPE_ID": 22,
      "transactioN_DESC": " Services (FED in ST Mode) "
    },
    {
      "transactioN_TYPE_ID": 18,
      "transactioN_DESC": " Services "
    },
    {
      "transactioN_TYPE_ID": 81,
      "transactioN_DESC": "Exempt goods"
    },
    {
      "transactioN_TYPE_ID": 82,
      "transactioN_DESC": "DTRE goods"
    },
    {
      "transactioN_TYPE_ID": 130,
      "transactioN_DESC": "Cotton ginners"
    },
    {
      "transactioN_TYPE_ID": 132,
      "transactioN_DESC": "Electric Vehicle"
    },
    {
      "transactioN_TYPE_ID": 134,
      "transactioN_DESC": "Cement /Concrete Block"
    },
    {
      "transactioN_TYPE_ID": 84,
      "transactioN_DESC": "Telecommunication services"
    },
    {
      "transactioN_TYPE_ID": 123,
      "transactioN_DESC": "Steel melting and re-rolling"
    },
    {
      "transactioN_TYPE_ID": 125,
      "transactioN_DESC": "Ship breaking"
    },
    {
      "transactioN_TYPE_ID": 115,
      "transactioN_DESC": "Potassium Chlorate"
    },
    {
      "transactioN_TYPE_ID": 178,
      "transactioN_DESC": "CNG Sales"
    },
    {
      "transactioN_TYPE_ID": 181,
      "transactioN_DESC": "Toll Manufacturing"
    },
    {
      "transactioN_TYPE_ID": 138,
      "transactioN_DESC": "Non-Adjustable Supplies"
    },
    {
      "transactioN_TYPE_ID": 139,
      "transactioN_DESC": "Goods as per SRO.297(|)/2023"
    }
  ]